# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-20.04'

strategy:
  matrix:
    Python37Torch190:
      python.version: '3.7'
      pytorch.version: '1.9.0'

    Python38Torch220:
      python.version: '3.8'
      pytorch.version: '2.2.0'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install numpy
    pip install torch==$(pytorch.version) --no-index -f https://download.pytorch.org/whl/cpu/torch_stable.html
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines
    pytest -v --pyargs entmax
  displayName: 'pytest'
